### ISSUE TITLE
The need for cobol syntax extension

### ISSUE THREAD

**Issue by kraabrsg** [OlegKunitsyn/gnucobol-debug#126]
Hi, this is rather a question than an issue, we would like to make a pli debugger extension and as starting point derive it from yours.
Wondering why there is a need for e.g. z open editor extension to have breakpoints available.

Thanks!

**Comment by GitMensch** [comment]
The extensions specifies languages it supports breakpoints for https://github.com/OlegKunitsyn/gnucobol-debug/blob/38ded147da5fc1a88cefabd89dbf4ae55138e22e/package.json#L48-L67 - and the COBOL language(s) are not available as a vscode built-in as [per docs](https://code.visualstudio.com/docs/languages/identifiers#_known-language-identifiers) - so you need a language extension to provide it
Otherwise you'd need to tell people to enable "Allow Breakpoints Anywhere" in their configuration.

In any case it will be useful for the user to have at least basic syntax highlighting and commonly this is separate from the debugger (some extensions combine everything into one).

Note: if you want full GDB support and "primarily" do the mapping to a generated C file and data wrapping (which is the core  of this extension) you may want to check out [Native Debug](https://github.com/WebFreak001/code-debug.git) [different license] and integrating features there - or {"extend" it](https://github.com/WebFreak001/code-debug/issues/314).
If you are free on the toolset you may consider requesting GDB 12+ and load a python extension within GDB for the wrapping - in this case the Debugging extension "only" has to use gdb/mi commands (much easier in general on the extension side, better performance and easier to fork extensions like native.debug), the actual wrapping would be done from within GDB.

**Comment by kraabrsg** [comment]
Well thank you for getting back on this, we have done a syntax highlighting in our own extension. We now use the free zos explorer from ibm (for debugging). But we want to get rid of this external program. We wiresharked the communication from zos explorer. 

So our main goal is to debug on the remote server -> https://code.visualstudio.com/api/extension-guides/debugger-extension#alternative-approach-to-develop-a-debugger-extension guessing
`DebugAdapterServer ` is the route to go.

I am not sure if GDB is needed here... The main goal is to send data an launch to the mainframe server, send data when starting debugging, etc.... Unterstanding the way debuggers are implemented in vscode is the hard part here....

**Comment by GitMensch** [comment]
Ah, in this case neither gnucobol-debug nor native.debug are useful, you likely are best-fitted by inspecting https://github.com/RechInformatica/rech-cobol-debugger (and possibly closing this question issue as it is not really related to this extension).

**Comment by kraabrsg** [comment]
> Ah, in this case neither gnucobol-debug nor native.debug are useful, you likely are best-fitted by inspecting https://github.com/RechInformatica/rech-cobol-debugger (and possibly closing this question issue as it is not really related to this extension).

Thanks will do!
