### ISSUE TITLE
Debugger works with Ububtu 20.04 on wsl2 (Win 10) :)

### ISSUE THREAD

**Issue by gfmoore** [OlegKunitsyn/gnucobol-debug#19]
First of all, sorry if this is not the correct way to do this, but I did search stack overflow and some did suggest open an issue and close it.

I just wanted to inform people that I've downloaded and installed the new Ubuntu 20.04 distro, loaded gnucobol 
sudo apt-get install gnucobol  
gives v2.2.0

loaded gdb
sudo apt-get install gdb
gives version 9.1

The debugger works from within wsl2 fine. Actually I just ran vscode (insiders) from windows start menu, opened my folder, changed to wsl2 folder (it asks which distro - I have both Ubuntu 18.04 and now 20.04 loaded) and debugged my program - don't forget to open the debug window.

So well done Oleg :)

**Comment by GitMensch** [comment]
The "correct way" would be to create a PR changing the README to include this info (so roadmap change to "native Win32" and somewhere a note about the working setup).
Although I'm now interested - @gfmoore could you try to get it work with WSL1 and afterwards with the [official MinGW binaries for GnuCOBOL}(https://www.arnoldtrembley.com/GnuCOBOL.htm) next?

**Comment by gfmoore** [comment]
wsl 1 won't work because it cannot read/write windows folders and probably some other things as well.
You need windows 10 fall edition at least I think, then switch to wsl 2
I wrote some links on issue 5 (near the bottom( 
https://github.com/OlegKunitsyn/gnucobol-debug/issues/5#issuecomment-618424185

wsl2 works in a very different way to wsl1 afaik - MS basically wrote it to work in a virtual machine I think. wsl 2 is the way to go - and is going to be updated in May.

As for doing a pull request, that's way out of my league. Never done it and I'd soil myself trying to do it right lol

Please remember I'm a newbie at all this stuff. :)

**Comment by GitMensch** [comment]
> wsl 1 won't work because it cannot read/write windows folders and probably some other things as well.

I use wsl1 since it came up in the insider's years ago, one of the points was *always* that wsl can access Windows directories (via auto-mount /mnt/x/), that it can start all win32 executable and has an environment conversion option (I later recognized that you can access wsl-only paths via hidden local auto-network share, that may worked since the beginning or not).

> You need windows 10 fall edition at least I think, then switch to wsl 2

[MS says](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/) that for non-insider you need to have version 2002 installed

... so @gfmoore could you please try to downgrade your working wsl2 to wsl1 and check if the plugin still works?

> As for doing a pull request, that's way out of my league. Never done it and I'd soil myself trying to do it right lol

This one is easy here at least for a single file: just use the <>code tab, go to the file you want to update (I'd say it is likely README.md), then click on "edit". GitHub informs you that it will create a fork under the hood for you where you actually edit the file. As soon as you're done you are prompted with the option to do a pull request. You definitely should give it a try :-)

**Comment by gfmoore** [comment]
Hi, with respect I think I'll leave my setup at wsl2. I cannot really see any reason to use wsl1 and I know that when I did  try this studd originally it didn't work because I was getting permission errors on my windows shares, not the sahres under linux shares, which is why I ended up learning about and switching to wsl2 :)
Wsl1 is basically a dead duck really imo.

As for the pull request, well I've given it a shot. I won't be offended if it's massively edited or even deleted. I've also now had to look into markdown! Man the things I've had to learn the last couple of weeks 😆

**Comment by GitMensch** [comment]
> I think I'll leave my setup at wsl2.

I didn't asked you to go back to wsl1 for long, just a one-time downgrade `wsl --set-version <Distro> 1`, then some tests, then upgrade again `wsl --set-version <Distro> 2`. In no case uninstall a distro or wsl (otherwise your settings would all vanish, which is not the case with the downgrad/upgrade; note: this also includes mounts (which worked perfectly fine for me on WSL1) so you're unlikely to see issues there...)

> I cannot really see any reason to use wsl1

There are multiple ones. The one that cannot be argued: WSL2 is a virtual machine that only works if you have a CPU with extended virtualization support, the BIOS not disabling it (I've seen multiple boards with this option turned of by default), OS setup to include the necessary features and if it is "only not activated" you'd still need to have the privileges to activate/install (vscode user works with nearly no access rights).
Other points like "even less hardware support" and "cannot use VirtualBox or other virtualization software together with WSL2" are likely going to vanish over time.

So my question stands: can you please test with WSL1?

**Comment by gfmoore** [comment]
@GitMensch/Simon: I have to let you know Simon, that the way you phrased your comments and requests made me feel uncomfortable. I am positive that you did not intend that consequence, but you came across as someone who did not respect my position. You are probably right in your comments, but I felt I was being coerced into an action that I had as nicely as I could implied that I did not want to take.

However, in order to put this to rest, I did downgrade my Ubuntu 20.04 to wsl 1, started code, reinstalled the extensions and tried to compile my code. As I had suspected I ran into permissions issues and I am not prepared to experiment any more in a direction I will not need to take in the future. I leave that to you.

![image](https://user-images.githubusercontent.com/22768967/80864399-3e756080-8c7a-11ea-811c-45c739afeef2.png)

I will now upgrade back to wsl 2 and reset my "tool chain".

:)

**Comment by GitMensch** [comment]
> I felt I was being coerced into an action that I had as nicely as I could implied that I did not want to take

I'm sorry, thanks for the feedback concerning my communication.

> I did downgrade my Ubuntu 20.04 to wsl 1, started code, reinstalled the extensions and tried to compile my code. As I had suspected I ran into permissions issues

Thank you for the note and the screenshot which now shows that with a fine setup there are definitely issues (on triggering compilation, not on the debug).

I do think that I'd have a workaround which possibly would get it to work (calling wslpath for file, but I don't know if that's possible via launch.json), but as you say further tests with wsl1 would need someone that has reason to get it working.
Thanks again for still trying.

**Comment by gfmoore** [comment]
:)
